//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordKeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetPersonalData
    {
        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateCode { get; set; }
        public string Zip { get; set; }
        public int PersonalRecords { get; set; }
        public System.DateTime TimeOfContact { get; set; }
        public string Notes { get; set; }
        public System.DateTime TimeCompleted { get; set; }
    }
}
