//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordKeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalRecord
    {
        public int PersonalRecords { get; set; }
        public int PersonalId { get; set; }
        public System.DateTime TimeOfContact { get; set; }
        public string Notes { get; set; }
        public System.DateTime TimeCompleted { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
