<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Person.aspx.cs" Inherits="RecordKeeping.Person" %>
<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <telerik:RadGrid ID="RadGrid1" runat="server" AllowFilteringByColumn="True" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" CellSpacing="-1" DataSourceID="PersonDS" GridLines="Both">
        <GroupingSettings CollapseAllTooltip="Collapse all groups">
        </GroupingSettings>
        <MasterTableView AutoGenerateColumns="False" DataKeyNames="PersonId" DataSourceID="PersonDS">
            <Columns>
                <telerik:GridBoundColumn DataField="PersonId" DataType="System.Int32" FilterControlAltText="Filter PersonId column" HeaderText="PersonId" ReadOnly="True" SortExpression="PersonId" UniqueName="PersonId">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="FirstName" FilterControlAltText="Filter FirstName column" HeaderText="FirstName" SortExpression="FirstName" UniqueName="FirstName">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="LastName" FilterControlAltText="Filter LastName column" HeaderText="LastName" SortExpression="LastName" UniqueName="LastName">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="Address1" FilterControlAltText="Filter Address1 column" HeaderText="Address1" SortExpression="Address1" UniqueName="Address1">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="Address2" FilterControlAltText="Filter Address2 column" HeaderText="Address2" SortExpression="Address2" UniqueName="Address2">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="City" FilterControlAltText="Filter City column" HeaderText="City" SortExpression="City" UniqueName="City">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="StateCode" FilterControlAltText="Filter StateCode column" HeaderText="StateCode" SortExpression="StateCode" UniqueName="StateCode">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="Zip" FilterControlAltText="Filter Zip column" HeaderText="Zip" SortExpression="Zip" UniqueName="Zip">
                </telerik:GridBoundColumn>
            </Columns>
        </MasterTableView>
    </telerik:RadGrid>
    <asp:SqlDataSource ID="PersonDS" runat="server" ConnectionString="<%$ ConnectionStrings:ExamplesDBConnectionString %>" DeleteCommand="DELETE FROM [Persons] WHERE [PersonId] = @PersonId" InsertCommand="INSERT INTO [Persons] ([FirstName], [LastName], [Address1], [Address2], [City], [StateCode], [Zip]) VALUES (@FirstName, @LastName, @Address1, @Address2, @City, @StateCode, @Zip)" SelectCommand="SELECT * FROM [Persons]" UpdateCommand="UPDATE [Persons] SET [FirstName] = @FirstName, [LastName] = @LastName, [Address1] = @Address1, [Address2] = @Address2, [City] = @City, [StateCode] = @StateCode, [Zip] = @Zip WHERE [PersonId] = @PersonId">
        <DeleteParameters>
            <asp:Parameter Name="PersonId" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="FirstName" Type="String" />
            <asp:Parameter Name="LastName" Type="String" />
            <asp:Parameter Name="Address1" Type="String" />
            <asp:Parameter Name="Address2" Type="String" />
            <asp:Parameter Name="City" Type="String" />
            <asp:Parameter Name="StateCode" Type="String" />
            <asp:Parameter Name="Zip" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="FirstName" Type="String" />
            <asp:Parameter Name="LastName" Type="String" />
            <asp:Parameter Name="Address1" Type="String" />
            <asp:Parameter Name="Address2" Type="String" />
            <asp:Parameter Name="City" Type="String" />
            <asp:Parameter Name="StateCode" Type="String" />
            <asp:Parameter Name="Zip" Type="String" />
            <asp:Parameter Name="PersonId" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
</asp:Content>
